### ISSUE TITLE
Order of class method tests for Owner should be changed

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/oo-my-pets#12]
In the "Class methods" section of `spec/owner_spec.rb`, the second test uses the `Owner.count` method, which itself is not mentioned until the third test. Therefore, the order of the second and third tests should be reversed.

This is a rewrite of issue #10.
Reported by @robjciaccio.

Pull request forthcoming.

@aturkewi

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestion. We adjusted the order of the Owner class method specs.

As always, thanks for contributing! 💙
