### ISSUE TITLE
consider using class variables instead of constants.

### ISSUE THREAD

**Issue by jilustrisimo** [learn-co-curriculum/oo-my-pets#14]
```
class Owner
  OWNERS = []
  attr_accessor :name, :pets
  attr_reader :species

  def self.reset_all
    OWNERS.clear
  end

  def self.all
    OWNERS
  end
```

Since `OWNERS` is being manipulated, should it not be a constant?

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestion. Both constants or class variables could work for this scenario.

Constants cannot re re-assigned (We cannot say `OWNERS = some_other_object`) but we are able to mutate the object the constant points to (`OWNERS = [];OWNERS.push(new_owner)`).

As always, thanks for contributing! 💙
