### ISSUE TITLE
Directions could use clarification

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/oo-my-pets#21]
Hey there again. 

These spec directions could use some editing/clarification. Under the Class methods, it includes initialize, but initialize is not a class method. This contradicts itself a couple lines down where it talks about initialize as an instance method. It would also be beneficial to line out which class methods are expected, the same way it is defined for instance methods.

Best,
Amanda

```Owner
  Class methods
    keeps track of the owners that have been created
    can count how many owners have been created
    can reset the owners that have been created
    can initialize an owner
  instance methods
    #species
      initializes with a species
      can't change its species
    #say_species
      can say its species
    #name
      can have a name
    #pets
      is initialized with a pets attribute as a hash with 3 keys```

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @helloamandamurphy.

We have updated the spec messages and tests for the Owner class and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
