### ISSUE TITLE
Test not clear

### ISSUE THREAD

**Issue by regilfillan** [learn-co-curriculum/oo-my-pets#25]
the owner_spec.rb file's section on the #species instance method says 
"initializes with a species"  makes me think it should take an argument of species, it could be more clear (like it is explicitly said in all the new pet instantiations' moods) that the owner species should actually  be set to human.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
