### ISSUE TITLE
buy_cat and buy_dog are misleading names

### ISSUE THREAD

**Issue by stephenkeating** [learn-co-curriculum/oo-my-pets#29]
I spent a long time trying to change the owners of dog names before figuring out that this method is just supposed to make a new cat/dog. That was really frustrating.

**Comment by sgharms** [comment]
@stephenkeating 

Could you please help clarify here? I think the part that could be adjusted would be:

> When an owner buys a new pet, the buy_cat/buy_dog methods take in an argument of a name. >You must take that name and do the following:
>
>Make a new instance of the appropriate pet, initializing it with that name and the owner who is >purchasing it.

The specs don't seem to suggest changing names, either.

Can you suggest what change might have helped you avoid this tangent?

**Comment by stephenkeating** [comment]
As I read this again, I think it makes sense. I was probably too focused on the first line and didn’t pay enough attention to the second. Sorry and thanks!

Stephen
310-938-4400

**Comment by sgharms** [comment]
OK, thanks for letting us know!
