### ISSUE TITLE
No green light

### ISSUE THREAD

**Issue by KerenLerner** [learn-co-curriculum/oo-my-pets#6]
I haven't gotten a green light for this despite submitting several days ago.  Thanks!

**Comment by AnnJohn** [comment]
Hi @fullstack212 this looks like it might be an engineering issue. Please use the Ask a Question tool and someone will get back to you right away! Thanks!

**Comment by KerenLerner** [comment]
Hi Ann. Ask A Question goes to my fellow students. I was under the
impression that Report an Issue was for engineering issues. Isn't there a
way to get this to the proper people without mixing it up with questions on
the content that go to fellow students?
